# SwiftLint Configuration
# Unified configuration for Swift projects
# For more information: https://github.com/realm/SwiftLint

# Paths to include in linting
included:
  - Sources
  - Plugins
  - Tests

# Paths to exclude from linting
excluded:
  - .build
  - .swiftpm
  - bin
  - Packages
  - Package.swift
  - Tests/LinuxMain.swift
  - "**/*.generated.swift"

# Opt-in rules (not enabled by default)
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_first_not_nil
  - empty_count
  - empty_string
  - explicit_init
  - fallthrough
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - last_where
  - literal_expression_end_indentation
  - modifier_order
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - nimble_operator
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prohibited_super_call
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - strict_fileprivate
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# Analyzer rules (require building your project)
analyzer_rules:
  - explicit_self
  - unused_declaration
  - unused_import

# Rules to disable
disabled_rules:
  - todo
  - trailing_comma
  - trailing_whitespace

# Rule configurations
line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true
  ignores_function_declarations: true
  ignores_interpolated_strings: true

file_length:
  warning: 500
  error: 1000
  ignore_comment_only_lines: true

function_body_length:
  warning: 50
  error: 100

function_parameter_count:
  warning: 6
  error: 8

type_body_length:
  warning: 300
  error: 500

type_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 50
    error: 60
  excluded:
    - T
    - ID

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - ID
    - url
    - URL
    - to
    - db
    - T

cyclomatic_complexity:
  warning: 10
  error: 20
  ignores_case_statements: true

nesting:
  type_level:
    warning: 2
    error: 3

large_tuple:
  warning: 3
  error: 4

# Custom rules
custom_rules:
  comments_space:
    name: "Space after comment"
    regex: "(^ *//\\w+)"
    message: "There should be a space after //"
    severity: warning

# Reporter type
reporter: "xcode"